version: "3.3"

services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
#    volumes:
#      - ./sql-data:/var/lib/postgresql/data
    restart: unless-stopped
